### ISSUE TITLE
Make stats configurable

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/tnc-network-site#11]

**Comment by kellyi** [comment]
The app currently has 3 boxes for stats:

<img width="935" alt="screen shot 2017-11-06 at 12 54 09 pm" src="https://user-images.githubusercontent.com/4165523/32455868-a284b10c-c2f1-11e7-8e54-e756611cd709.png">

We're going to keep 3 as the static number, but make each area configurable. If fewer are included in the config file, we'll show an empty box; if more are configured we'll skip showing the extras.
