### ISSUE TITLE
Configure Travis to generate static asset bundle on release

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/tnc-network-site#12]
Ideally the bundle could be attached to a release on Github.

**Comment by kellyi** [comment]
#35 configures the project's Travis file to have it build on making new releases; we now need to set up a machine user to generate proper credentials for the `$GITHUB_TOKEN` here --
 https://github.com/CoastalResilienceNetwork/tnc-network-site/blob/develop/.travis.yml#L17 -- and store them in Travis.

**Comment by kellyi** [comment]
Successful build here:

https://travis-ci.org/CoastalResilienceNetwork/tnc-network-site/builds/303157946

Successful release upload here:

https://github.com/CoastalResilienceNetwork/tnc-network-site/releases/tag/1.0.3

TravisCI's now set up to deploy site artifacts on git flow releases.
