### ISSUE TITLE
Fix StatsView slideout animation

### ISSUE THREAD

**Issue by kellyi** [CoastalResilienceNetwork/tnc-network-site#29]
Previously the StatsView disappeared with a slideout animation on the user's first interaction with the map or the region list. While reviewing #22 we discovered a regression bug whereby the slideout was no longer happening for Macbook Pro sized viewports (but still seemed to work for some larger screen sizes).

It's happening on `develop`, too, so we should make a fix to restore the slideout functionality added in #15.

**Comment by kellyi** [comment]
According to git bisect this was introduced in 987a0155911808f3f198c9e4ba7c2a2dc522089a

**Comment by kellyi** [comment]
To simplify things a bit I'm going to try implementing this with jQuery `slideToggle`.

**Comment by ajrobbins** [comment]
Takes the point from https://github.com/azavea/civic-apps/issues/278
