### ISSUE TITLE
Create network page documentation

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/tnc-network-site#34]
Create documentation for network page configuration and deployment, and post on wiki.

**Comment by kellyi** [comment]
Shares a point with #33

**Comment by kellyi** [comment]
Created a page documenting `config.json` here: https://github.com/CoastalResilienceNetwork/tnc-network-site/wiki/Configuration

**Comment by kellyi** [comment]
We should also update the git flow instructions to add a note about gathering out-of-band changes to the configuration into proper commits before making a new release.

**Comment by kellyi** [comment]
Draft documentation of deployment steps is here:

https://github.com/CoastalResilienceNetwork/tnc-network-site/wiki/Deployment
